package kz.epam.command;

public enum CommandEnum {
    NO_COMMAND, LOGIN_FORM, LOGIN, LOGOUT, REGISTRATION, REGISTRATION_FORM, USER_PAGE,
    UPDATE_USER_DETAILS, UPDATE_USER_PASSWORD, SELECT_DATE, SELECT_PRODUCTS, ADD_TO_CART, REVIEW_CART,
    CHECKOUT, CONFIRM_ORDER, ADMIN_PAGE, SHOW_ALL_ORDERS, SHOW_TASKS,
    SHOW_ALL_REQUESTS, SHOW_AVAILABLE_PRODUCTS, UPDATE_PRODUCT_LIST, SHOW_PRODUCT_INFO,
    UPDATE_PRODUCT_INFO, ADD_NEW_PRODUCT, SHOW_INCOME, SHOW_ANNUAL_INCOMES,
    SHOW_ALL_INCOMES, CANCEL_ORDER;
}
